sim:hcal_barrel:
  extends: .det_benchmark
  stage: simulate
  parallel:
    matrix:
      - PARTICLE: ["piplus", "piminus", "kplus", "kminus", "kshort", "klong", "muon", "antimuon", "proton"]
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_particles.sh ${PARTICLE}

sim:hcal_barrel:scan:
  extends: .det_benchmark
  stage: simulate
  parallel:
    matrix:
      - PARTICLE: ["muon", "antimuon", "proton"]
        E: ["0.25", "0.5", "1", "2", "3", "4", "7", "15", "20"]
  script:
    - bash benchmarks/barrel_hcal/run_hcal_barrel_energy_scan.sh ${PARTICLE} ${E}

bench:hcal_barrel:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel"]
  parallel:
    matrix:
      - PARTICLE: ["piplus", "piminus", "kplus", "kminus", "kshort", "klong", "muon", "antimuon", "proton"]
  script:
    - ls -lhtR sim_output/
    - rootls -t sim_output/sim_hcal_barrel_${PARTICLE}.edm4hep.root
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_particles_analysis.cxx+("'${PARTICLE}'")'

bench:hcal_barrel:scan:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:hcal_barrel:scan"]
  parallel:
    matrix:
      - PARTICLE: ["muon", "antimuon", "proton"]
  script:
    - ls -lhtR sim_output/
    - sort -n sim_output/hcal_barrel_energy_scan_points_${PARTICLE}_*.txt > sim_output/hcal_barrel_energy_scan_points_${PARTICLE}.txt
    - root -b -q 'benchmarks/barrel_hcal/scripts/hcal_barrel_energy_scan_analysis.cxx+("'${PARTICLE}'")'

collect_results:barrel_hcal:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:hcal_barrel", "bench:hcal_barrel:scan"]
  script:
    - ls -lrht
    - echo " FIX ME" 

