sim:zdc:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/zdc/run_zdc_particles.sh --particle $PARTICLE
  parallel:
    matrix:
      - PARTICLE: ["neutron", "photon"]

bench:zdc_benchmark:
  extends: .det_benchmark
  stage: benchmarks
  needs: 
    - ["sim:zdc"]
  script:
    - root -b -q -x  'benchmarks/zdc/scripts/analysis_zdc_particles.cxx+("sim_output/sim_zdc_'${PARTICLE}'.edm4hep.root", "results/far_forward/zdc/'${PARTICLE}'")'
  parallel:
    matrix:
      - PARTICLE: ["neutron", "photon"]

collect_results:zdc:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:zdc_benchmark"]
  script:
    - ls -lrht
