image: ${BENCHMARKS_REGISTRY}/${BENCHMARKS_CONTAINER}${BENCHMARKS_SIGIL}${BENCHMARKS_TAG}

variables:
  DETECTOR: epic
  DETECTOR_CONFIG: epic_craterlake
  GITHUB_PR: ''
  GITHUB_REPOSITORY: ''
  GITHUB_SHA: ''
  SNAKEMAKE_FLAGS: '--cache'

workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "webide"'
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'

default:
  tags:
    - phy-scratch
  artifacts:
    expire_in: 72 hours 
    paths:
      - .local/lib
      - .local/bin
      - .local/include
      - .snakemake/log
      - logs
      - results
      - config
      - .env
      - summary.txt
    reports:
      dotenv: .env
    when: always

stages:
  - status-pending
  - config
  - initialize
  - simulate
  - calibrate
  - benchmarks
  - collect
  - deploy
  - status-report

.status:
  image: curlimages/curl:latest
  rules:
    - if: $GITHUB_SHA !~ /^$/ # when GITHUB_SHA non-empty
  script:
    - |
      curl \
        -X POST \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${GITHUB_REPO_STATUS_TOKEN}" \
        "https://api.github.com/repos/${GITHUB_REPOSITORY}/statuses/${GITHUB_SHA}" \
        -d '{"state":"'"${STATE}"'",
             "target_url":"'"${CI_PIPELINE_URL}"'",
             "description":"'"$(TZ=America/New_York date)"'",
             "context":"eicweb/detector_benchmarks ('"${BENCHMARKS_TAG}"', '"$DETECTOR_CONFIG"')"
            }' ;
  retry:
    max: 2
    when:
      - runner_system_failure


benchmarks:detector:pending:
  stage: status-pending
  extends: .status
  variables:
    STATE: "pending"
  when: always

common:setup:
  stage: config
  before_script:
  script:
    - |
      if [[ "${COMMON_BENCH_VERSION}" == "" ]] ; then
        export COMMON_BENCH_VERSION="main" 
      fi
      echo "COMMON_BENCH_VERSION = ${COMMON_BENCH_VERSION}" 
      echo "COMMON_BENCH_VERSION=${COMMON_BENCH_VERSION}" >> .env
      git clone --depth 1 -b "${COMMON_BENCH_VERSION}" https://github.com/eic/common_bench.git .local 
      rm -rf .local/.git
      echo "BENCHMARKS_TAG: ${BENCHMARKS_TAG}"
      echo "BENCHMARKS_CONTAINER: ${BENCHMARKS_CONTAINER}"
      echo "BENCHMARKS_REGISTRY: ${BENCHMARKS_REGISTRY}"
    - source .local/bin/env.sh
    - mkdir_local_data_link sim_output
    - mkdir_local_data_link EPIC
    - mkdir -p results
    - mkdir -p config
    - eic-info
    - |
      flock --nonblock /scratch/garbage-collect.lock \
        ./garbage-collect.py --target-size 500G --symlink-roots-dir /scratch \
        || true

.det_benchmark:
  needs:
    - ["common:setup"]
  before_script:
    - source .local/bin/env.sh
    - source /opt/detector/epic-main/bin/thisepic.sh
    - ls -lrtha 
    - ln -s "${LOCAL_DATA_PATH}/sim_output" sim_output
    - ln -s "${LOCAL_DATA_PATH}/EPIC" EPIC
    # snakemake support
    - mkdir "${DETECTOR_CONFIG}"
    - ln -s "${LOCAL_DATA_PATH}/sim_output" "${DETECTOR_CONFIG}/sim_output"
    - ln -s "../results" "${DETECTOR_CONFIG}/results"
    - mkdir -p "$SNAKEMAKE_OUTPUT_CACHE"
    - ls -lrtha
  retry:
    max: 2
    when:
      - runner_system_failure

include: 
  - local: 'benchmarks/panda/config.yml'
  
deploy_results:
  allow_failure: true
  extends: .det_benchmark
  stage: deploy
  needs:
    - "collect_results:panda"
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 results/metadata.json
    - find results -print | sort | tee summary.txt
    - |
      if [ ! -x "$(command -v pelican)" ] ; then
        wget https://dl.pelicanplatform.org/7.13.0/pelican_Linux_x86_64.tar.gz ;
        sha256sum -c <(echo '38ac8548c67302299e50a1b81c159ed418e90d84a6606ddd377fd2c8b164d114 pelican_Linux_x86_64.tar.gz') ;
        tar zxf pelican_Linux_x86_64.tar.gz ;
        export PATH=${PWD}/pelican-7.13.0:${PATH} ;
      fi
    - mv results pipeline-$CI_PIPELINE_ID; tar cf pipeline-$CI_PIPELINE_ID.tar pipeline-$CI_PIPELINE_ID/; mv pipeline-$CI_PIPELINE_ID results
    - pelican object copy pipeline-$CI_PIPELINE_ID.tar $OSDF_ENDPOINT$OSDF_OUTPUT_PREFIX/pipeline-$CI_PIPELINE_ID.tar
  retry:
    max: 2
    when:
      - runner_system_failure

benchmarks:detector:success:
  stage: status-report
  dependencies: []
  extends: .status
  variables:
    STATE: "success"
  after_script:
    # Cleanup scratch space
    - rm -rfv $LOCAL_DATA_PATH
  when: on_success

benchmarks:detector:failure:
  stage: status-report
  dependencies: []
  extends: .status
  variables:
    STATE: "failure"
  when: on_failure

pages:
  stage: deploy
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" && $CI_SERVER_HOST != "eicweb.phy.anl.gov"'
  cache:
    paths:
      - node_modules/
  image: node:latest
  script:
    - mkdir public && cp doc/main.html public/index.html
  artifacts:
    paths:
      - public
