image: ${BENCHMARKS_REGISTRY}/${BENCHMARKS_CONTAINER}${BENCHMARKS_SIGIL}${BENCHMARKS_TAG}

variables:
  DETECTOR: epic
  DETECTOR_CONFIG: epic_craterlake
  GITHUB_PR: ''
  GITHUB_REPOSITORY: ''
  GITHUB_SHA: ''
  SNAKEMAKE_FLAGS: '--cache'
  RM: ''

workflow:
  name: '$PIPELINE_NAME'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - if: '$CI_PIPELINE_SOURCE == "webide"'
    - if: '$CI_PIPELINE_SOURCE == "trigger"'
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_TAG'

default:
  tags:
    - phy-scratch
  artifacts:
    expire_in: 72 hours 
    paths:
      - .local/lib
      - .local/bin
      - .local/include
      - .snakemake/log
      - logs
      - results
      - config
      - .env
      - summary.txt
    reports:
      dotenv: .env
    when: always

stages:
  - config

common:setup:
  stage: config
  before_script:
  script:
    -|
      ps aux
      exit 1
      uptime
      df -h
      cat /proc/mounts
      touch test
      sleep 60
      stat test
      sleep 60
      stat test
      sleep 60
      cat test
      stat test
      if [ -n "${RM}" ] ; then rm -rf $RM ; fi
      exit 0
      cat >filter_broken.py <<EOF
      import sys
      import ROOT
      ROOT.gEnv.SetValue("TFile.Recover", 0)
      for filename in sys.stdin:
          filename = filename.rstrip()
          bad = False;
          try:
              f = ROOT.TFile(filename)
              bad = bad or f.IsZombie()
          except OSError:
              bad = True
          if bad:
              print(filename)
      EOF
      :>list
      if [ -n "${REPAIR}" ]; then
        echo "removing broken ROOT files from cache"
        for file in $(find /scratch/snakemake-cache -type f); do
          if file -b "$file" | grep -E '^ROOT file' >/dev/null; then
            echo "$file" >> list
          fi
        done
        echo "located $(cat list | wc -l) ROOT files"
        cat list | python filter_broken.py | tee broken
        cat broken | xargs --no-run-if-empty rm -v
      fi
      echo "removing broken symlinks"
      find `realpath /scratch` -xtype l -print -delete
      echo "listing most offending directories"
      find `realpath /scratch` -type d -links 2 -print0 | (du -sL --files0-from=- || true) | sort -n > /tmp/df
      #echo "listing cached entries by size"
      #find `realpath /scratch` -type l -print0 | (du -sL --files0-from=- || true) | sort -n > /tmp/df
      #find `realpath /scratch` -type f -print0 | du -s --files0-from=- || true | sort -n > /tmp/df
      head /tmp/df
      tail -n 1000 /tmp/df
      df -h
