sim:bic_pid:
  extends: .det_benchmark
  stage: simulate
  image: $BENCHMARKS_REGISTRY/eic_ci$BENCHMARKS_SIGIL$BENCHMARKS_TAG
  variables:
    DETECTOR_CONFIG: epic_craterlake
  parallel:
    matrix:
      - PARTICLE: ["e-", "pi-"]
        ANGLE: ["45to135deg"]
        ENERGY: ["1GeV"]
        INDEX_RANGE: [
          "0 9",
          "10 19",
          "20 29",
          "30 39",
          "40 49",
          "50 59",
          "60 69",
          "70 79",
          "80 89",
          "90 99",
        ] 
  script:
    - export DETECTOR_CONFIG=epic_craterlake
    - |
      snakemake $SNAKEMAKE_FLAGS --cores 1 \
        $(seq --format="sim_output/bic_pid/${DETECTOR_CONFIG}/${PARTICLE}/${ENERGY}/${ANGLE}/${PARTICLE}_${ENERGY}_${ANGLE}.%04.f.eicrecon.edm4eic.root" ${INDEX_RANGE})


bench:bic_pid:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:bic_pid"]
  image: $BENCHMARKS_REGISTRY/eic_ci$BENCHMARKS_SIGIL$BENCHMARKS_TAG
  variables:
    CUDA_VISIBLE_DEVICES: ""
    DETECTOR_CONFIG: epic_craterlake
  before_script:
    - source .local/bin/env.sh
    - ls -lrtha
    - ln -s "${LOCAL_DATA_PATH}/sim_output" sim_output
    - mkdir -p "${DETECTOR_CONFIG}"
    - ln -s "${LOCAL_DATA_PATH}/sim_output" "${DETECTOR_CONFIG}/sim_output"
    - ln -s "../results" "${DETECTOR_CONFIG}/results"
    - mkdir -p "$SNAKEMAKE_OUTPUT_CACHE"
    - find sim_output/bic_pid/${DETECTOR_CONFIG} | head -50 || true
    - ls -lrtha
  script:
    - |
      command -v python3.10
      python3.10 -V

      python3.10 -m venv .venv
      source .venv/bin/activate

      python -m pip install --upgrade pip setuptools wheel
      python -m pip install snakemake
      python -m pip install -r benchmarks/bic_pid/requirements.txt

      python -c "import sys, uproot, awkward as ak, dask, dask_awkward as dak, numpy as np, pandas as pd, tensorflow as tf, tf2onnx; print(sys.version); print('uproot', uproot.__version__); print('awkward', ak.__version__); print('dask', dask.__version__); print('dask_awkward', dak.__version__); print('numpy', np.__version__); print('pandas', pd.__version__); print('TF', tf.__version__); print('tf2onnx', tf2onnx.__version__)"
      snakemake $SNAKEMAKE_FLAGS --cores 1 results/${DETECTOR_CONFIG}/bic_pid


collect_results:bic_pid:
  extends: .det_benchmark
  stage: collect
  needs:
    - "bench:bic_pid"
  when: always
  image: $BENCHMARKS_REGISTRY/eic_ci$BENCHMARKS_SIGIL$BENCHMARKS_TAG
  variables:
    DETECTOR_CONFIG: epic_craterlake
  script:
    - export DETECTOR_CONFIG=epic_craterlake
    - ls -lrht
    - mv results{,_save}/
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output results/${DETECTOR_CONFIG}/bic_pid
    - mv results{_save,}/
