sim:bic_pid:
  extends: .det_benchmark
  stage: simulate
  image: $BENCHMARKS_REGISTRY/eic_ci$BENCHMARKS_SIGIL$BENCHMARKS_TAG
  variables:
    DETECTOR_CONFIG: epic_craterlake
  parallel:
    matrix:
      - PARTICLE: ["e-", "pi-"]
        ANGLE: ["45to135deg"]
        ENERGY: ["1GeV"]
        INDEX_RANGE: [
          "0 9",
          "10 19",
          "20 29",
          "30 39",
          "40 49",
          "50 59",
          "60 69",
          "70 79",
          "80 89",
          "90 99",
        ]
  script:
    - export DETECTOR_CONFIG=epic_craterlake
    - |
      snakemake $SNAKEMAKE_FLAGS --cores 1 \
        $(seq --format="sim_output/bic_pid/${DETECTOR_CONFIG}/${PARTICLE}/${ENERGY}/${ANGLE}/${PARTICLE}_${ENERGY}_${ANGLE}.%04.f.eicrecon.edm4eic.root" ${INDEX_RANGE})
    - mkdir -p transferred_sim_output
    - cp -aL sim_output/bic_pid transferred_sim_output/
  artifacts:
    when: always
    paths:
      - transferred_sim_output/
      - .snakemake/log/


bench:bic_pid:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - "common:setup"
    - "sim:bic_pid"
  image: $BENCHMARKS_REGISTRY/eic_tf$BENCHMARKS_SIGIL$BENCHMARKS_TAG
  variables:
    CUDA_VISIBLE_DEVICES: ""
    DETECTOR_CONFIG: epic_craterlake
  before_script:
    - source .local/bin/env.sh
    - ls -lrtha
    - find transferred_sim_output/bic_pid | head -50 || true
    - mkdir -p sim_output
    - cp -a transferred_sim_output/bic_pid sim_output/
    - mkdir -p "${DETECTOR_CONFIG}"
    - ln -s ../sim_output "${DETECTOR_CONFIG}/sim_output"
    - ln -s ../results "${DETECTOR_CONFIG}/results"
    - mkdir -p "$SNAKEMAKE_OUTPUT_CACHE"
    - find sim_output/bic_pid | head -50 || true
    - ls -lrtha
  script:
    - python -m pip install snakemake
    - python -m pip install -r benchmarks/bic_pid/requirements.txt
    - snakemake $SNAKEMAKE_FLAGS --cores 1 results/${DETECTOR_CONFIG}/bic_pid


collect_results:bic_pid:
  extends: .det_benchmark
  stage: collect
  needs:
    - "common:setup"
    - "bench:bic_pid"
  when: always
  image: $BENCHMARKS_REGISTRY/eic_ci$BENCHMARKS_SIGIL$BENCHMARKS_TAG
  variables:
    DETECTOR_CONFIG: epic_craterlake
  script:
    - export DETECTOR_CONFIG=epic_craterlake
    - ls -lrht
    - mv results{,_save}/
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output results/${DETECTOR_CONFIG}/bic_pid
    - mv results{_save,}/