sim:b0_tracker:
  stage: simulate
  extends: .det_benchmark
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 sim_output/b0_tracker/${DETECTOR_CONFIG}/sim_forward_protons.edm4hep.root

bench:b0_tracker:
  stage: benchmarks
  extends: .det_benchmark
  needs:
    - ["sim:b0_tracker"]
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 results/far_forward/b0/${DETECTOR_CONFIG}/hits_eta.pdf

results:b0_tracker:
  extends: .det_benchmark
  stage: collect
  needs: 
    - ["bench:b0_tracker"]
  script:
    - ls -lrht
