.script:sim:femc_photon:
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 sim_output/femc_photon/epic_craterlake_rec_photon_${P}GeV.edm4eic.root

.script:bench:femc_photon:
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores $MAX_CORES_PER_JOB results/epic_craterlake/femc_photon

sim:femc_photon:
  extends: .det_benchmark
  stage: simulate
  rules:
    - if: $BENCHMARK_RUNNER != "htcondor"
  parallel:
    matrix:
      - P: 10
      - P: 20
      - P: 30
      - P: 40
      - P: 50
      - P: 60
      - P: 70
      - P: 80
  timeout: 1 hours
  script:
    - !reference [.script:sim:femc_photon, script]
  retry:
    max: 2
    when:
      - runner_system_failure

bench:femc_photon:
  extends: .det_benchmark
  stage: benchmarks
  rules:
    - if: $BENCHMARK_RUNNER != "htcondor"
  needs: ["sim:femc_photon"]
  script:
    - !reference [.script:bench:femc_photon, script]

sim_bench:femc_photon:
  extends: .det_benchmark:htcondor
  stage: benchmarks
  rules:
    - if: $BENCHMARK_RUNNER == "htcondor"
  script:
    - !reference [.script:bench:femc_photon, script]

collect_results:femc_photon:
  extends: .det_benchmark
  stage: collect
  needs:
    - job: "bench:femc_photon"
      optional: true
    - job: "sim_bench:femc_photon"
      optional: true
  when: always
  script:
    - ls -al
    - mv results{,_save}/ # move results directory out of the way to preserve it
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output results/epic_craterlake/femc_photon
    - mv results{_save,}/
