tof:sim_tof_hits:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/tof/btof_hits.sh --sim-only
#    - bash benchmarks/tof/etof_hits.sh --sim-only

tof:plot_hits:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["tof:sim_tof_hits"]
  script:
    - bash benchmarks/tof/btof_hits.sh --analysis
 #   - bash benchmarks/tof/etof_hits.sh --analysis
