tof:sim_tof_hits:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/tof/tof_hits.sh --sim-only

bench:tof:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["tof:sim_tof_hits"]
  script:
    - bash benchmarks/tof/tof_hits.sh --analysis

bench:materialscan:tofonly:
  stage: benchmarks
  extends: .det_benchmark
  script:
    - mkdir results/tof/
    - echo ".x benchmarks/tof/materialScanPhi.cxx(-3.15, +3.15, 0.002, 51.5, 60., 0.0001, 51.5, 60., 120., 120.)" | materialScan ${DETECTOR_PATH}/${JUGGLER_DETECTOR}.xml -interactive
    - mv materialScanPhi.png results/tof/materialScanPhi_TOFOnly.png
    - mv materialScanPhi.pdf results/tof/materialScanPhi_TOFOnly.pdf
    - echo ".x benchmarks/tof/materialScanPhi.cxx(-0.15, +0.15, 0.002, 51.5, 60., 0.0001, 51.5, 60., 120., 120.)" | materialScan ${DETECTOR_PATH}/${JUGGLER_DETECTOR}.xml -interactive
    - mv materialScanPhi.png results/tof/materialScanPhi_TOFOnlyZoom.png
    - mv materialScanPhi.pdf results/tof/materialScanPhi_TOFOnlyZoom.pdf

