tof:sim_tof_hits:
  extends: .det_benchmark
  stage: simulate
  script:
    - bash benchmarks/tof/tof_hits.sh --sim-only

bench:materialscan:tof:
  extends: .det_benchmark
  stage: benchmarks
  script:
    - echo ".x benchmarks/others/materialScan.cxx(-4.5, +4.5, 0.01, 750., 0.0, 51., 120., 120.)" | materialScan ${DETECTOR_PATH}/${JUGGLER_DETECTOR}.xml -interactive
    - mkdir results/images/
    - mv materialScan.png results/images/materialScanNoTOF.png
    - mv materialScan.pdf results/images/materialScanNoTOF.pdf
    - echo ".x benchmarks/others/materialScan.cxx(-4.5, +4.5, 0.01, 750., 0.0, 60., 120., 120.)" | materialScan ${DETECTOR_PATH}/${JUGGLER_DETECTOR}.xml -interactive
    - mv materialScan.png results/images/materialScanTOF.png
    - mv materialScan.pdf results/images/materialScanTOF.pdf

bench:tof:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["tof:sim_tof_hits"]
  script:
    - bash benchmarks/tof/tof_hits.sh --analysis
