sim:zdc_lyso:
  extends: .det_benchmark
  allow_failure: true # https://github.com/eic/detector_benchmarks/issues/178
  stage: simulate
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 zdc_lyso_local
  retry:
    max: 2
    when:
      - runner_system_failure

collect_results:zdc_lyso:
  extends: .det_benchmark
  allow_failure: true # https://github.com/eic/detector_benchmarks/issues/178
  stage: collect
  needs:
    - "sim:zdc_lyso"
  when: always
  script:
    - ls -lrht
    - mv results{,_save}/ # move results directory out of the way to preserve it
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output zdc_lyso_local
    - mv results{_save,}/
