sim:zdc_lyso:
  extends: .det_benchmark
  stage: simulate
  script:
    - snakemake --cores 1 run_all_locally
  retry:
    max: 2
    when:
      - runner_system_failure

collect_results:zdc_lyso:
  extends: .det_benchmark
  stage: collect
  needs:
    - "sim:zdc_lyso"
  script:
    - ls -lrht
