sim:femc_pi0:
  extends: .det_benchmark:sim
  parallel:
    matrix:
      - P: 10
      - P: 20
      - P: 30
      - P: 40
      - P: 50
      - P: 60
      - P: 70
      - P: 80
  timeout: 2 hours
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 sim_output/femc_pi0/epic_craterlake_rec_pi0_${P}GeV.edm4eic.root

bench:femc_pi0:
  extends: .det_benchmark:bench
  needs: ["sim:femc_pi0"]

collect_results:femc_pi0:
  extends: .det_benchmark:collect
  needs: ["bench:femc_pi0"]
