sim:femc_pi0:
  stage: simulate
  extends: .det_benchmark
  parallel:
    matrix:
      - P: 10
      - P: 20
      - P: 30
      - P: 40
      - P: 50
      - P: 60
      - P: 70
      - P: 80
  timeout: 1 hours
  script:
    - snakemake --cores 1 sim_output/femc_pi0/epic_craterlake_rec_pi0_${P}GeV.edm4eic.root
  retry:
    max: 2
    when:
      - runner_system_failure

bench:femc_pi0:
  stage: benchmarks
  extends: .det_benchmark
  needs: ["sim:femc_pi0"]
  script:
    - snakemake --cores 1 results/epic_craterlake/femc_pi0

collect_results:femc_pi0:
  stage: collect
  needs: ["bench:femc_pi0"]
  script:
    - ls -al
    - mv results{,_save}/ # move results directory out of the way to preserve it
    - snakemake --cores 1 --delete-all-output results/epic_craterlake/femc_pi0
    - mv results{_save,}/
