sim:beamline:
  extends: .det_benchmark
  stage: simulate
  script:
    - |
      snakemake $SNAKEMAKE_FLAGS --cores 2 \
        sim_output/beamline/beamlineTestlocal.edm4hep.root

bench:beamline:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - ["sim:beamline"]
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 2 beamline_local

collect_results:beamline:
  extends: .det_benchmark
  stage: collect
  needs:
    - "bench:beamline"
  script:
    - ls -lrht
    - mv results{,_save}/ # move results directory out of the way to preserve it
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output beamline_local
    - mv results{_save,}/
