SIM_DIRECTORY:   "LowQ2_G4out/"
RECO_DIRECTORY:  "LowQ2_ReconOut/"
MODEL_DIRECTORY: "LowQ2_Model/"

# Run Snakemake for the training
train:LOWQ2:
  extends: .det_benchmark
  stage: calibrate
  script:
    - snakemake --cores 8 ${MODEL_DIRECTORY}"trainedData.root" --configfile config.yml 
  
