neutron:simulate:
  stage: simulate
  extends: .phy_benchmark
  needs: ["common:detector"]
  parallel:
    matrix:
      - P: 20
      - P: 30
      - P: 40
      - P: 50
      - P: 60
      - P: 70
      - P: 80
  timeout: 1 hours
  script:
    - snakemake --cores 1 sim_output/neutron/epic_craterlake_rec_neutron_${P}GeV.edm4hep.root 
  retry:
    max: 2
    when:
      - runner_system_failure

neutron:analyze:
  stage: analyze
  extends: .phy_benchmark
  needs: ["neutron:simulate"]
  script:
    - mkdir -p results/epic_craterlake
    - python benchmarks/neutron/analysis/neutron_plots.py results/epic_craterlake/neutron

neutron:results:
  stage: collect_results
  needs: ["neutron:analyze"]
  script:
    - ls -al
