sim:nhcal_acceptance:
  extends: .det_benchmark
  stage: simulate
  parallel:
    matrix:
      - ENERGY: ["1GeV", "5GeV", "10GeV"]
        INDEX_RANGE: ["0 4","5 9"]
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 $(for INDEX in $(seq -f '%02.0f' $INDEX_RANGE); do echo sim_output/nhcal_acceptance/E${ENERGY}/sim_epic_backward_hcal_only.${INDEX}.edm4hep.root; done)

bench:nhcal_acceptance_analysis:
  extends: .det_benchmark
  stage: benchmarks
  needs:
    - "sim:nhcal_acceptance"
  parallel:
    matrix:
      - ENERGY: ["1GeV", "5GeV", "10GeV"]
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 1 results/nhcal_acceptance/analysis_epic_backward_hcal_only_E${ENERGY}_combined_10files.pdf

collect_results:nhcal_acceptance:
  extends: .det_benchmark
  stage: collect
  needs: 
    - "bench:nhcal_acceptance_analysis"
  parallel:
    matrix:
      - ENERGY: ["1GeV", "5GeV", "10GeV"]
  script:
    - ls -lrht
    - mv results{,_save}/ 
    - snakemake $SNAKEMAKE_FLAGS --cores 1 --delete-all-output results/nhcal_acceptance/analysis_epic_backward_hcal_only_E${ENERGY}_combined_10files.pdf
    - mv results{_save,}/
