sim:output_branch_size_scan:
  stage: simulate
  extends: .det_benchmark
  script:
    bash generate.sh
    
    

bench:output_branch_size_scan:
  stage: benchmarks
  extends: .det_benchmark
  needs:
    - ["sim:output_branch_size_scan"]
  script:
    bash output_branch_size_scan.sh
    

results:output_branch_size_scan:
  stage: collect
  extends: .det_benchmark  
  needs: 
    - ["bench:output_branch_size_scan"]
  script:
    
