sim:zdc_muon:
  stage: simulate
  extends: .det_benchmark
  needs: ["common:detector"]
  parallel:
    matrix:
      - P: 50
  timeout: 1 hours
  script:
    - snakemake --cores 1 sim_output/zdc_muon/epic_zdc_sipm_on_tile_only_sim_mu-_${P}GeV.edm4hep.root 
  retry:
    max: 2
    when:
      - runner_system_failure

bench:zdc_muon:
  stage: benchmarks
  extends: .det_benchmark
  needs: ["sim:zdc_muon"]
  script:
    - mkdir -p results/epic_craterlake
    - python benchmarks/zdc_muon/analysis/muon_plots.py results/epic_zdc_sipm_on_tile_only/zdc_muon

collect_results:zdc_muon:
  stage: collect
  needs: ["bench:zdc_muon"]
  script:
    - ls -al
