sim:zdc_photon:
  extends: .det_benchmark
  stage: simulate
  parallel:
    matrix:
      - P: 20
      - P: 30
      - P: 50
      - P: 70
      - P: 100
      - P: 150
      - P: 200
      - P: 275
  script:
    - snakemake $SNAKEMAKE_FLAGS --cores 5 sim_output/zdc_photon/epic_zdc_sipm_on_tile_only_rec_zdc_photon_${P}GeV_{0,1,2,3,4}.edm4eic.root
  retry:
    max: 2
    when:
      - runner_system_failure

bench:zdc_photon:
  extends: .det_benchmark
  stage: benchmarks
  needs: ["sim:zdc_photon"]
  script:
    - mkdir -p results/epic_zdc_sipm_on_tile_only
    - python benchmarks/zdc_photon/analysis/zdc_photon_plots.py results/epic_zdc_sipm_on_tile_only/zdc_photon

collect_results:zdc_photon:
  extends: .det_benchmark
  stage: collect
  needs: ["bench:zdc_photon"]
  script:
    - ls -al
