sim:zdc_photon:
  stage: simulate
  extends: .det_benchmark
  needs: ["common:detector"]
  parallel:
    matrix:
      - P: 20
      - P: 30
      - P: 50
      - P: 70
      - P: 100
      - P: 150
      - P: 200
      - P: 275
  timeout: 1 hours
  script:
    - snakemake --cores 1 sim_output/zdc_photon/epic_zdc_sipm_on_tile_only_rec_zdc_photon_${P}GeV.edm4hep.root 
  retry:
    max: 2
    when:
      - runner_system_failure

bench:zdc_photon:
  stage: benchmarks
  extends: .det_benchmark
  needs: ["sim:zdc_photon"]
  script:
    - mkdir -p results/epic_zdc_sipm_on_tile_only
    - python benchmarks/zdc_photon/analysis/zdc_photon_plots.py results/epic_zdc_sipm_on_tile_only/zdc_photon

collect_results:zdc_photon:
  stage: collect
  extends: .det_benchmark
  needs: ["bench:zdc_photon"]
  script:
    - ls -al
