name: trigger-eicweb

on: [ push ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - uses: eic/trigger-gitlab-ci@v2
      id: trigger
      with:
        url: https://eicweb.phy.anl.gov
        project_id: 399
        token: ${{ secrets.EICWEB_DETECTOR_BENCHMARKS_TRIGGER }}
        ref_name: master
        variables: |
          DETECTOR_CONFIG=epic_brycecanyon
          GITHUB_REPOSITORY=${{ github.repository }}
          GITHUB_SHA=${{ github.event.pull_request.head.sha || github.sha }}
          GITHUB_PR=${{ github.event.pull_request.number }}
